### ISSUE TITLE
EditorConfig

### ISSUE THREAD

**Issue by cg505** [kotct/dot#10]
Add support for `.editorconfig` files. See http://editorconfig.org/.

**Comment by rye** [comment]
Here's [some reference](https://github.com/editorconfig/editorconfig-emacs).

So in order to do this we have to think about `indent-tabs-mode`.  EditorConfig sets it magically, but certain language modes have their own `indent-tabs-mode` variables. (E.g. `ruby-indent-tabs-mode`)

We should discuss the best ways to deal with these variables.  For one, we should always make sure that `smart-tabs-mode` is turned on whenever `indent-tabs-mode` is turned on, which we can add as a hook to `editorconfig-custom-hooks`.

**Comment by rye** [comment]
In `rye/duff`, I solved the problem regarding tabs variables by [adding a hook](https://github.com/rye/duff/blob/4edea52fcd19ea97d40f88719cc78a93c15fbf17/.emacs.d/lisp/hooks/editorconfig.el#L1-L5), though if Smart Tabs is used, this won't matter because it should be turned on.

More apposite is my work on [turning off `smart-tabs-mode` if `indent-tabs-mode` is set](https://github.com/rye/duff/blob/4edea52fcd19ea97d40f88719cc78a93c15fbf17/.emacs.d/lisp/hooks/editorconfig.el#L7-L10).  I think EditorConfig only sets `indent-tabs-mode`, but I'm not sure.

**Comment by cg505** [comment]
I disagree with respect to `smart-tabs-mode`: the user may be working on a project that does not use smart tabs.

I think hooks are the right approach for setting language-specific variables.

**Comment by cg505** [comment]
Actually we can use `editorconfig-indentation-alist`.

**Comment by cg505** [comment]
Just a note: we want to gracefully handle installation of the editor-config and executable and the case in which it's not installed.

**Comment by rye** [comment]
@cg505 there is no intelligent way to discern through EditorConfig whether the user wants smart tabs.  I suppose the only case we can really, truly handle is if the user wants to disable tabs. (See [this](https://github.com/rye/duff/blob/4edea52fcd19ea97d40f88719cc78a93c15fbf17/.emacs.d/lisp/hooks/editorconfig.el#L7-L10).)

**Comment by rye** [comment]
So basically this just needs to install it and then turn off `smart-tabs-mode` if `indent-tabs-mode` is `nil`, which will happen whenever a user loads a file and EditorConfig sets that variable.

**Comment by rye** [comment]
Or, should we just always keep `smart-tabs-mode` active?  If `indent-tabs-mode` is not truthy, `smart-tabs-mode` doesn't seem to do anything.

**Comment by rye** [comment]
Since EditorConfig has its own core built into the Emacs plugin, I don't think we should force the user to install EditorConfig's C core, perhaps just notify them that it's a thing.

**Comment by rye** [comment]
RFC @cg505, let me know what you think of all of this.
