### ISSUE TITLE
key combo for dired

### ISSUE THREAD

**Issue by samontea** [kotct/dot#32]
By default `dired` is unbound to a keycombo in emacs. I think we should bind it to `C-x C-d` because list `list-directory` is just a less useful version of `dired`. Any opposition?

**Comment by rye** [comment]
I'm not averse to this, though it feels as though this customization would best be put in your own configuration as `C-x C-d` is currently bound to `ido-list-directory`, which is better than `list-directory`.

If `dired` is better (which is debatable, because `ido-list-directory` accomplishes many of the tasks that `dired` does but in a more compact and featureful way) we can switch. I'd be interested to hear @cg505's opinion on the matter.

**Comment by samontea** [comment]
Alternatively we could bind it to `ido-dired` which i just learned is a thing.

**Comment by rye** [comment]
`C-x d` is bound to `ido-dired`... 😮

**Comment by cg505** [comment]
btw i'm not sure if this is something i had to change in my config but if you do `C-j` on a directory in `ido-find-file` it opens the directory in dired

**Comment by rye** [comment]
> i'm not sure if this is something i had to change in my config

It wasn't. I get the same behavior&mdash;`C-j` on a directory launches `dired` in that directory.
