### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by cg505** [kotct/dot#49]
As this becomes a more major project with actual potential for wider usage, it would be good to set up our licensing and everything correctly.

**Comment by rye** [comment]
I think the MIT license is acceptable.  GitHub says that [our contributors so far](https://github.com/kotct/dot/graphs/contributors) are @rye, @cg505, and @samontea in that order.  In order to make sure that everything is straightened out, I need all of the aforementioned to approve using the MIT license and a joint copyright with our names in alphabetical order.

(The specific copyright notice would look like `Copyright (c) 2017 Christopher Cooper, Samuel Mercier, and Kristofer Rye` in all files where it is placed.)

**Comment by cg505** [comment]
idc much except that a copyright in each file will be annoying as fuck

**Comment by rye** [comment]
Agreed.  We should just put one license notice in the root of the repository.

**Comment by cg505** [comment]
This sounds good to me. CC @samontea for approval.

**Comment by rye** [comment]
By the way, I intend to list collaborators in alphabetical order of last name, not order of contribution.   Just wanted to make sure that was clear.

**Comment by samontea** [comment]
lgtm 👍

**Comment by cg505** [comment]
@rye feel free to move forward with this then

**Comment by rye** [comment]
Will do as soon as I'm logged in.
